### ISSUE TITLE
bbl on AWS should use newer m4 instance types

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-bootloader#112]
AWS recently added a new AZ to us-east-1 which does not support the `m3.xlarge` instance type:

```
CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Your requested instance type (m3.xlarge) is not supported in your requested Availability Zone (us-east-1b). Please retry your request by not specifying an Availability Zone or choosing us-east-1d, us-east-1a, us-east-1c, us-east-1e.","ok_to_retry":false}
```

This lack of support is not super surprising as `m3` has been replaced with `m4` types for some time. Could y'all bump to the `m4` instances to get around this error?

**Comment by evanfarrar** [comment]
We enumerated the instance types we were able to create soon after we learned of the AZ and it didn't have a lot of vm types to choose from (c1.medium and m2.4xlarge). In addition the new AZ did not work correctly with cloudformation (but this has since been fixed). As a result we've been working around this so far with the newly introduced `--aws-bosh-az` flag (new in 2.4.1) which allows you to avoid the offending AZ once you are unlucky enough to discover it.

If AWS intended for users to migrate m3 to m4, it would be strange to only tell them 1/5th of the time when they get loadbalanced to a particular AZ. As it stands their documentation seems to advocate for either instance type equally. We could change

**Comment by ljfranklin** [comment]
@evanfarrar the `--aws-bosh-az` is problematic for us as we have many environments in CI and the AZ letters are not the same across different account. Meaning us-east-1a for me is not necessarily that same as us-east-1a for you ([doc](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions-availability-zones)).

**Comment by evanfarrar** [comment]
Yes. And amazon does not provide a way even see what instance types are available without booting the type so there truly is no way to identify this bad zone except trial and error.

**Comment by evanfarrar** [comment]
Hey @ljfranklin 

bosh-deployment has solved this indirectly by also mistakenly assuming m3 was deprecated. In any case, the director is now an `m4.large` by default in bbl v.3.0.4.
