### ISSUE TITLE
Support DNS management for Concourse

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/bosh-bootloader#114]
BBL makes deploying concourse on GCP a breeze. At the moment, though, I have to manually configure DNS records. It would be nice if bbl could help me create and manage DNS records.

**Comment by evanfarrar** [comment]
@enocom while I also loathe this one manual step, it would still be one manual step because I can't make less than one manual step without also buying the domain for you. For CF there are a lot of fiddly ips/subdomains to manage, but concourse just has the one domain name and one IP. What do you think would be easier about making an NS record with the five randomly chosen gcloud DNS vs. making one cname for the randomly chosen IP?

We've considered this before, but I've intentionally avoided it because it seems less wonderful than the CF equivalent and on par with what exists. Closing this for now, but still open to the idea if I can understand the advantage.
