### ISSUE TITLE
bbl fails to launch compilation VM for Windows stemcell on us-east-1

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-bootloader#135]
We bbl'd up a new AWS environment in us-east-1 and got the following error while trying to do a BOSH deploy:

```
Error: Unknown CPI error 'Unknown' with message 'Your requested instance type 
(c3.large Windows) is not supported in your requested Availability Zone 
(us-east-1a). Please retry your request by not specifying an Availability Zone 
or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1e.' in 'create_vm' CPI method
```
We fixed this by manually updating the cloud-config and switching our compilation instance type to a `c4`.

This is with `bbl` version:
```
$ bbl version
bbl 3.1.0 (darwin/amd64)
```

**Comment by evanfarrar** [comment]
Hey @zankich 

This is due to the fact that a particular zone in us-east-1 (your account refers to it as "a") does not have a lot of the types of VMs that AWS offers. Recently another bbl user filed this as a BOSH bug which caused them to switch m3 to m4 for the director in BOSH deployment, but that won't help if your compilation VMs refer to a type that the zone does not support.

c3 and m3 are not deprecated according to AWS documentation, and you will find if you attempt to deploy CF to this zone that a lot of the VM types that CF needs are also missing.

If you really need to use us-east-1, there is a flag to choose which availability zone the bosh director is created in, which you could use to avoid "a". Unfortunately, there is no programmatic way for us to tell ahead of time which AZ is the limited-vm-type zone, as AWS does not expose VM availability in their API. Also if you run the same command on other AWS accounts, what you now see as "a" will be named something else.
