### ISSUE TITLE
Add monitoring without redeploying bosh

### ISSUE THREAD

**Issue by groenborg** [cloudfoundry/bosh-bootloader#138]
Hello
Me and my coworker @sharor have had concourse running in kubernetes for a while, but a lot of things were not working as intended when running concourse in a container, so we wanted to try with bosh, and found this wonderful repo. 

We have deployed bosh and concourse on aws and would like to change our bosh deployment (and concourse) to include monitoring without redeploying bosh. Both on machine and service level if possible. 

how do we do that? 🙂  

we found this issue #64 but weren't sure how to do it. Is it understood correctly that it is the bosh.yml file we need to configure, and is there a way we can extract it?

**Comment by evanfarrar** [comment]
For Concourse monitoring you could add to the concourse manifest a syslog drain. Each job in the manifest (atc/tsa/worker) could also include something like syslog-release to drain off logs: https://github.com/cloudfoundry/syslog-release

You should be able to supply an `-o` file to `bbl up` to add syslog-release to the director without recreating everything, using this example ops file as a start: https://github.com/cloudfoundry/bosh-deployment/blob/master/syslog.yml but substituting all variables for actual values. The bosh.yml we use is just bosh-deployment frozen at a specific SHA1, the specific SHA1 is mentioned in the release notes of each release. If you ever end up totally recreating your director in the future it would be a good idea to use the `--no-director` feature so that you can use bosh and bosh-deployment directly: https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/advanced.md

**Comment by groenborg** [comment]
@evanfarrar So we can call `bbl up -o  datadog.yml` to update the configuration, and bbl will only apply the update and not recreate the whole thing? :)
