### ISSUE TITLE
bbl create-lbs --type cf deletes lbs created for concourse in GCP

### ISSUE THREAD

**Issue by virajago** [cloudfoundry/bosh-bootloader#146]
Am trying to setup CF on GCP using concourse running on GCP.
Installed bosh on GCP using bbl
Created lbs for concourse using bbl
created concourse on GCP using bbl
then ran bbl create-lbs --type cf which deleted the load balancer and external IP created for concourse earlier

**Comment by genevievelesperance** [comment]
You cannot have cf load balancers and concourse load balancers on the same environment.

Deleting the old lbs for the new ones is the expected behavior.

**Comment by virajago** [comment]
Is there a technical limitation or is it a bbl design limitation? Any future plans to include this?

**Comment by evanfarrar** [comment]
There is nothing that would make this impossible, it just hasn't been a priority to consider how this would affect the UX to support both simultaneously. It hasn't come up that often, but we could begin to look at enabling this.

Most users using bbl manually are creating non-ephemeral environments (production) and usually want to keep director passwords separate from their CI. Most users using BBL in an automated fashion will create multiple isolated directors so that their pipeline does not need to manage the director with a mutex.

**Comment by zankich** [comment]
I believe this is a divergence of behavior between GCP and AWS.

AWS will fast fail if you try to switch the load balancer type: https://github.com/cloudfoundry/bosh-bootloader/blob/9bbecba4b9aee1d5e599be55fa819cf91be61335/commands/aws_create_lbs_test.go#L579

**Comment by evanfarrar** [comment]
BBL AWS using terraform does exhibit the same behavior. BBL AWS via Terraform will be the default in the future.

Because we were able to seemingly just "do what the user wanted" we didn't put a fast fail guard on this as terraform has no problem moving to the new state "for free." I'd like to leave open the possibility of supporting both on one director, if we can better understand what user intent is when they call "create-lbs" a second time.

**Comment by varun7447** [comment]
Is this mean we need to have separate BOSH for Concourse and CF?? I am facing same issue in AWS. I was able to setup Concourse without any issues and when trying to run `bbl create-lbs` it is trying to destroy the already existing resources and failing with below error

_* aws_security_group.concourse_lb_internal_security_group (destroy): 1 error(s) occurred:

* aws_security_group.concourse_lb_internal_security_group: DependencyViolation: resource sg-f6b87XXX has a dependent object
        status code: 400, request id: 85c038a6-03e0-4b61-b002-0bb6e2b725d8_

**Comment by genevievelesperance** [comment]
For now you will need separate environments if you would like a cf deployment and s concourse deployment. This applies to any iaas.

**Comment by varun7447** [comment]
Is there a recommended way to upgrade production CF using concourse? I am thinking how can you use concourse if cannot be used with in the same environment,? Do I still use traditional bosh deploy?

**Comment by evanfarrar** [comment]
I would recommend you *create* your production bosh director in concourse, and have nothing shared between environments. For example: https://github.com/cloudfoundry/cf-deployment-concourse-tasks

**Comment by tcrockett1138** [comment]
Until support is added to deploy cf & concourse to the same environment (or even if this support is never added), it would be nice if bbl _could_ warn that it is going to tear down the lbs and ask if you want to continue.

The side-effect of this is then a new flag would need to exist to allow non-interactive, similar to bosh -n.
