### ISSUE TITLE
bbl should be able to configure load balancer to forward HTTPS traffic to Gorouter instead of just HTTP

### ISSUE THREAD

**Issue by flawedmatrix** [cloudfoundry/bosh-bootloader#148]
Hey there,

The routing team has noticed that bbl brings up a GCP load balancer that only forwards HTTP traffic to gorouter, but gorouter in CF deployment is pre-configured to terminate SSL connections.
https://github.com/cloudfoundry/bosh-bootloader/blob/9bbecba4b9aee1d5e599be55fa819cf91be61335/terraform/gcp/fixtures/gcp_template_cf_lb.tf#L339

In order to have the GCP load balancer forward HTTPS traffic to gorouter, we needed to manually update the load balancer configuration on the Google Cloud console.

We would like the ability to have bbl do this for us without too much manual intervention.

Thanks,
Edwin and @belinda-liu

**Comment by evanfarrar** [comment]
@flawedmatrix I'm pretty sure it is true that we expect to terminate HTTPS at the load balancer and forward HTTP, but I'm going to go through the steps to deploy bbl+cf to verify that.

I am guessing you want to pass through TCP to the router so it can terminate HTTPS, or maybe something broke without us noticing? What change, exactly, do you make to the console to fix it?

**Comment by evanfarrar** [comment]
@flawedmatrix @belinda-liu
BBL sets up the load balancer to terminate SSL and forward HTTP.

I know the gorouter can terminate SSL though. What exactly do you change in GCP to achieve what you want? Do you set up a TCP proxy or simply change the port?

**Comment by shashwathi** [comment]
@evanfarrar : We want to terminate HTTPS both LB and Gorouter. Currently GCP is configured to terminate HTTPS at LB so we need to update the backend service to forward HTTPS traffic to gorouter.

>  maybe something broke without us noticing?

Nothing broke on your side. We want to encrypt the leg between LB and gorouter. 

>  What change, exactly, do you make to the console to fix it?

In GCP console, under LB backend service configuration there is an option to HTTP or HTTPS traffic. We are recommending to choose HTTPs instead of HTTP.

Regards
@belinda-liu and @shashwathi

**Comment by genevievelesperance** [comment]
@shashwathi When you change the LB backend service for HTTPS traffic, what do you do to the associated HTTP health check?

**Comment by shashwathi** [comment]
@genevievelesperance 

> When you change the LB backend service for HTTPS traffic, what do you do to the associated HTTP health check?

HTTP Health check remain the same and it's independent of forwarding HTTPS traffic because health check port is 8080 and tls port is 443 for gorouter.

**Comment by genevievelesperance** [comment]
Interesting. When we try to leave the HTTP health check on the backend service after changing the traffic, we get this error:
```
* google_compute_backend_service.router-lb-backend-service: Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.healthChecks[0]': 'https://www.googleapis.com/compute/v1/projects/cf-infras/global/httpHealthChecks/httpsforwarding-cf'. HttpHealthCheck might not be used with HTTPS/HTTP2 backend service, invalid
```

**Comment by shashwathi** [comment]
@genevievelesperance : 

I think we noticed something very similar when we updated backend service to do HTTPS. For some unfortunate reasoning GCP does not allow altering backend service from HTTP-> HTTPS, you need to create a new backend service. I would give that a try. 

Regards
Shash

**Comment by genevievelesperance** [comment]
When we `bbl create-lbs` for the first time, terraform creates all new resources. With terraform, we create the router-lb backend service and assign it a health check. 

In the GCP console you can create a backend service with HTTPS protocol and an HTTP health check, but from terraform, you get the error I mentioned above about incompatibility.

We cannot use an HTTPS health check because the gorouter's 8080 port has a HTTP listener.

Since the google api returned the incompatibility error (and not terraform), we may need to wait for GCP to support this combination.

**Comment by genevievelesperance** [comment]
The fix is in: https://github.com/cloudfoundry/bosh-bootloader/commit/d920512d84166d0e6d7aacf82e8053bb1bdc54c1#diff-e46eff6efcdf4934424cb3a01ffeba61
