### ISSUE TITLE
Workflow for adding CredHub to your Director

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-bootloader#149]
Hi All!

As CredHub gets closer to GA, it would be great if `bbl` provided an easy workflow for co-locating CredHub on your Director. `bbl up --ops-file ./bosh-deployment/credhub.yml` gets mostly there, the tricky part is pulling the credhub CLI password out of the bbl state file.

Any thoughts on adding a `bbl up --credhub` and `bbl credhub-password` or similar?

**Comment by ljfranklin** [comment]
Looks this was already in the Icebox: https://www.pivotaltracker.com/story/show/143450825. +1 from CAPI team if that helps prioritization 👍

**Comment by evanfarrar** [comment]
Yeah, that would be pretty neat. Most of our work since GCP support has been in support of Credhub, of which BBL v3 with bosh-deployment was a major part, allowing us to consume the Credhub configuration via an ops file and to factor out director credentials for our own eventual credhub integration.

The BOSH team did not think it was a good idea to fix external-ip-not-recommended.yml to work with credhub, so we've had to begin work on jumpboxes instead, and have iced Credhub until we can migrate everyone to jumpbox based BOSH directors.
