### ISSUE TITLE
bbl v3.2.3 cannot extract the ssh-key from a bbl-state.json created with a previous version of bbl

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-bootloader#151]
- We have multiple bbl'ed up bosh directors that are managed using concourse tasks that run with a shared docker image
- We upgraded to bbl v3.2.3 in the shared docker image to recreate one of the bosh directors in order to get an AWS TCP load balancer
- This upgrade caused an orthogonal failure in our pipeline: a different task which depended on the `bbl ssh-key` to communicate with a director that had not been recreated failed with the message `Could not retrieve the ssh key, please make sure you are targeting the proper state dir.` like [this](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/ensure-transition-env-is-clean/builds/24).

The other environment was also bbl'ed up with an earlier v3.x.x `bbl`, so we did not expect to see this issue.

**Comment by evanfarrar** [comment]
Hey @jaresty I think the 

3.2.3+ and the stemcell it came with, a new user with a new SSH key has been created, so we started pulling it from a new field in the statefile. This error message tells me perhaps `bbl up` was not run yet against the director with 3.2.3.

I can fix the bug here, so that when the next version, v3.2.5, sees that a statefile's version is pre-3.2.3 it will pull from the old place, but you should be able to get unstuck yourself by running up against everything with 3.2.3.

**Comment by jaresty** [comment]
Hey @evanfarrar thanks for the suggestion!  In fact, we are already unstuck -- we are using `jq` to extract the sshKey from the old bbl-state location for both directors and it's working fine.  This issue is mostly for your information--thank you for prioritizing a fix!
