### ISSUE TITLE
Support aws access keys from IAM Profiles or allow arg for token

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/bosh-bootloader#153]
If not provided on the cli, bbl should source aws-access-key-id and aws-secret-access-key from the IAM metadata url (when running on an ec2) or allow the user to specify the aws_security_token to be specified so that we can execute bbl without creating actual IAM users and instead rely on the IAM Instance Profile security model.

**Comment by evanfarrar** [comment]
Hello!

We've currently got a story in our backlog for this: https://www.pivotaltracker.com/story/show/145499709

Among other best practices for AWS we were pointed to in the AWS Benchmark by the Center for Internet Security: https://www.pivotaltracker.com/epic/show/3527899

In the scheme of priorities we had this at the end of that epic, but that's only because we had originally felt some FUD about BOSH's support for this before I knew it was actually well supported by BOSH. If you feel a more urgency for this story in particular before the other stories in the epic, I'm interested in hearing about it.

**Comment by zachgersh** [comment]
hey @johnmcteague - I believe we've taken care of this (and it has been accepted). Going to close this and would love your feedback on whether this works for you in the latest bbl.
