### ISSUE TITLE
`bbl cloud-config` prints two identical networks

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/bosh-bootloader#159]
Hi,

When I run `bbl cloud-config` the `networks` section contains two networks, `private` and `default` that have identical properties. Not a big deal but seems a bit odd.

**Comment by genevievelesperance** [comment]
On GCP?

**Comment by kkallday** [comment]
Yeah I was deploying to GCP. It might affect other IaaSes too.

**Comment by genevievelesperance** [comment]
Yeah it appears both AWS and GCP have identical private/default networks.

**Comment by evanfarrar** [comment]
This is an intentional transition plan: many sample and user made manifests still reference private but we'd like to move towards naming this network default, and possibly actually making it the default when no network is specified as a feature in BOSH.

Does this cause you an issue? Did you find a manifest that attempts to use both (or even two bosh deployments you'd *like* to use together that use both)?

**Comment by kkallday** [comment]
No problem - didn't know this was intentional.
