### ISSUE TITLE
bbl destroy --force

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-bootloader#167]
It would be nice to have `--force` flag for `bbl destroy` command that will destroy infrastructure ignoring possible errors.

My case: I did `bbl up` with incorrect availability zone `europe-west1-a` - there is no such zone in GCP. The command failed. Then I run `bbl destroy` and it failed too, without removing current setup. I would expect `bbl destroy` to restore my state to the blank one.

Solved manually by deleting `bbl-state.json`.

**Comment by evanfarrar** [comment]
Hello!

Thanks for the suggestion. While we will keep it in mind, I think in this instance we'd rather you never get in that weird state to begin with. We will add some guards for this particular case so that no bbl state gets created when there is really nothing to be destroyed. We've prioritized this.

bbl destroy --force may still be an issue for users who have lost / deleted infrastructure and just want to finish the process, or for users who simply don't want to / can't log into their BOSH director to delete deployments. But it has been intentional to fail out if users did not completely clean out VMs in their VPC.
