### ISSUE TITLE
AWS eu-west-2 region is not supported

### ISSUE THREAD

**Issue by bahatelos** [cloudfoundry/bosh-bootloader#187]
The AWS eu-west-2 region seems to be missing from a few places so the bbl cannot cope with it.
The first hurdle is: nat_template_builder.go where the AMI map goes:
...
us-west-2      ="ami-77a4b816"
eu-west-1      ="ami-c0993ab3"
eu-central-1   ="ami-0b322e67"
...

Interestingly, there is no error returned:

mac:~/ bbl up --aws-access-key-id ${AWS_ACCESS_KEY} --aws-secret-access-key ${AWS_SECRET_KEY} --aws-region eu-west-2 --iaas aws
step: checking if keypair "keypair-bbl-env-ladoga-2017-08-27t20-00z" exists
step: creating keypair
step: validating whether stack needs to be migrated
step: generating terraform template

the following errors occurred:
exit status 1
Some output has been redacted, use `bbl latest-error` to see it or run again with --debug for additional debug output,
open /var/folders/mj/j_l3ql3j17gcm6lr8cfpgsgc0000gn/T/367401551/terraform.tfstate: no such file or directory

mac:~/ bbl latest-error

mac:~/ bbl latest-error --debug

Regards,
Andreas

**Comment by genevievelesperance** [comment]
What version of terraform are you using?

The `nat_template_builder.go` file is not used once the migration from cloudformation -> terraform happened for AWS in `bbl 4.0.0`.

The file that has the AMIs is https://github.com/cloudfoundry/bosh-bootloader/blob/master/terraform/aws/template_generator.go#L12-L25

If there were a region issue, you would see an error saying that region/zone does not exist or is not supported.

The reason you are not seeing output from `bbl latest-error` is because the failure happened before terraform was run.

If you upgrade to terraform >= 0.9.7, your issue may be resolved.
