### ISSUE TITLE
Instructions aren't present for getting started with bbl

### ISSUE THREAD

**Issue by awmartin** [cloudfoundry/bosh-bootloader#205]
The getting started links present in the README include deploying Concourse and Cloud Foundry, but they all assume you've run `bbl up`. There do not seem to be explicit instructions for how to deploy the bosh director with `bbl up`; no guidance is to be found.

For example, in the [GCP - Deploying Cloud Foundry](https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md) reference, the words "bbl up" don't even appear on that page.

For first-time users, this doesn't seem to be an ideal experience. Perhaps just a note in the README on running `bbl up` and the appropriate considerations for the given IaaS would be helpful.

**Comment by evanfarrar** [comment]
I think we may have overreacted to the opposite criticism: that there were several subtly different sets of duplicated docs in cf-deployment's repo and in our repo. We removed much of our documentation and referred to cf-deployment's docs instead, which don't fully explain the options you have for using bbl.

Our docs should probably link to docs.cloudfoundry.org instead of readmes in repos whenever possible. Hopefully soon cf-deployment docs will also be there soon.

https://docs.cloudfoundry.org/deploying/aws/setup_bosh_aws.html

This also shows to me that docs.cloudfoundry.org should have a GCP deployment guide and we should draft the Azure BOSH deployment documentation (Azure load balancers are almost ready to release).

**Comment by awmartin** [comment]
Yeah, I see two general problems. One is not knowing basic concepts for bbl. A newcomer may not even know that "bbl up" is the entry point. Even a generalized set of steps could help just to introduce what the tool is doing with what basic commands.

The second is inconsistency. As I'm following the CF on GCP instructions, there are oddities in my experience so far:

- Difference between GCP Project Name and Project ID is not noted and results in a googleapi error when providing the wrong one.
- `create-lbs` fails because it requires arguments that aren't documented in the `create-lbs` help (e.g. for GCP service account, GCP project name, etc.)

If every GCP command needs these arguments, then that could be documented in bbl instead of the linked docs. Not sure if the right thing is to PR into all the different repos around the bbl experience.

Also, the AWS instructions both in docs.cloudfoundry.org and in bosh-bootloader both do not mention `create-lbs`, even though the help string for `create-lbs` mentions AWS.

Sorry to nitpick, but it's been quite a journey to use this from scratch vis a vis docs. I'm kinda making it up as I go, and it's just the first two commands. :-/

**Comment by evanfarrar** [comment]
I think these are all good points. Some we have solutions in progress to address and some we do not yet. Reviving some of our old getting started documentation would be nice, I am a little sad that the cf-deployment docs have lost some of the copy-pasteability that the BBL version of the docs once had. Is this a sufficient tour of the commands to put in the readme such that the rest could be gleaned from BBL's online help?:

```
# Create a VPC and a BOSH director
bbl up --iaas gcp                                                 \
           --gcp-service-account-key mykey.json \
           --gcp-region us-west1
# Create load balancers for Cloud Foundry
bbl create-lbs --type cf             \
                         --cert my.cert    \
                        --key my.key       \
                        --domain cf.example.com
# Set all necessary variables to target your BOSH director
eval "$(bbl print-env)"
# deploy Cloud Foundry
git clone github.com/cloudfoundry/cf-deployment && \
     bosh deploy cf-deployment/cf-deployment.yml 
# now update your dns for cf.example.com to use the DNS servers in`bbl lbs`
```
This is _mostly_ real, but I've taken the liberty of documenting what is about to be true for `bbl up`. I also want to see how you feel about this "mockup" where online help leads the user:
```
$ bbl
If you are looking to get started, create a new environment with "bbl up".

Usage:
  bbl [GLOBAL OPTIONS] COMMAND [OPTIONS]
<truncated>

$ bbl up
<truncated>

Finished! You can now run:
    eval "$(bbl print-env)"
to target your BOSH director or
    bbl create-lbs
to create load balancers for Cloud Foundry or Concourse.
```


The docs on docs.cloudfoundry.org don't mention create-lbs because Load balancers we create are a little bit tied to cf-deployment. CF release is BOSH 1.0, and cloud config which we rely on to make a single unified experience is a BOSH 2.0 feature. We developed bbl to be a little bit forward leaning, we did not think we'd be waiting here in the future 6 months ago when we set out that way. Once cf-deployment is GA, the official docs will talk about create-lbs.

RE: The two required arguments on create-lbs that are not in online help. One of which (project-id) is a bug that a fix for is in flight for, the other is a new requirement we have failed to document (service account key). The bugfix will be to retrieve Project ID from the Service Account Key, so the sometimes subtle difference between Project Name and Project ID will stop being something we need to document.

**Comment by joshzarrabi** [comment]
I believe that the documentation has substantially improved since this issue was written, both in this repo and cf-deployment. I am going to close it, but feel free to reopen if you feel this is still an issue @awmartin
