### ISSUE TITLE
Old ops files will always be reused 

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh-bootloader#211]
When doing `bbl up` with an ops file, the ops file will be used to create the BOSH director.
If you redo `bbl up` without the ops file, bbl will still use the ops file and say `no deployment changes`.

I would like to see a redeployment without the old ops file.
Wdyt?

**Comment by evanfarrar** [comment]
Hey Kiemes,

This is a bit obtuse, but there _is_ a way out of this.
```
bbl up --ops-file ''
```
Since bbl 5.3+, you can also find and delete your ops file and control the full arguments to `bosh create-env` by looking in your state directory.

**Comment by Kiemes** [comment]
So you have to explicitly override the ops file, I see.
Is this intuitive?

I fixed the issue locally for me by deleting the generated `previous-user-ops-file.yml` and also removed the entry `userOpsFile` from bbl state file.

However, I would like to see bbl to not consider old ops files when not specified in the `bbl up` command.

**Comment by evanfarrar** [comment]
It's not intuitive, but I also didn't want users to have to remember exactly how an environment was configured in order to simply rotate keys in the case of a CVE, destroy it because it is unused, or upgrade the stemcell again in the case of a CVE. If `up` "forgets" what ops files you have, then the user has to remember them in all those situations as well, because the bosh CLI requires them.

To be intuitive and still meet that goal, we'd need full CRUD to interact with ops-files, which would complicate BBL quite a bit, and possibly make it nearly as complex as BOSH itself. Instead, I plan to deprecate the flag `--ops-file` in a future release and use the filesystem to provide those full CRUD semantics and the `create-director.sh` to allow users to inspect explicitly which ops files they are using in the environment without losing that ability to interact with an environment without remembering the full set of environment specific flags.

**Comment by evanfarrar** [comment]
We're planning on deprecating the --ops-file flag to bbl. It was very hard to determine:
1) what the ops file was appliying to
2) which bosh create-env (jumpbox or director) it applied to
3) what other ops files were applying
4) whether this was a permanent choice or would be reverted later
5) how to remove ops files
6) in what order ops files would be applied
7) how to inject new variables for ops files 

Now the recommended way to pass ops files is to edit `create-director.sh`. You can reference ops files in `bosh-deployment` directly, remove ops files, control the order of ops files and supply additional variables.
