### ISSUE TITLE
[feature][aws] Switch from classic ELBs to Network Load Balancers

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-bootloader#228]
Network load balancers have a number of advantages over classic ELBs, see http://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html#network-load-balancer-benefits

Most prominent: adding the same instance with multiple ports to the same LB and improved performance and health checking.

Can we please switch to Network LBs instead of using classic ELBs?
related: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/73

**Comment by evanfarrar** [comment]
I've been trying to drive in this direction; to ask as many operators and PMs as I can this week if we should switch to NLBs. I haven't heard a lot of objections so far or reasons ELBs are better for CF's 80/443 ports. Terraform _just_ fixed their NLB implementation a week or two ago so now it is fully possible for us to use. We've switched already to using NLBs for our concourse LBs, and I much prefer letting the user work with bosh's excellent cert setting/defaulting/updating mechanisms rather than re-implement that in BBL.

I will send out a cf-dev topic soon for further feedback, but it looks likely.

**Comment by voelzmo** [comment]
Awesome, thanks!

**Comment by cdutra** [comment]
@voelzmo It seems there's a [limit of 50 listeners](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-limits.html) per Network Load Balancer. This won't work for the CF TCP Load Balancer which creates 100 listeners from 1024-1123 ports.
I believe we could still change the CF Router and CF SSH Load Balancers to Network.
What do you think?

**Comment by voelzmo** [comment]
I guess this isn't very relevant anymore, so I'll go ahead and close it now.
