### ISSUE TITLE
Does bbl enforce vsphere user to have a resource pool? 

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry/bosh-bootloader#296]
Missing --vsphere-vcenter-rp.

**Comment by rowanjacobs** [comment]
Currently, yes. We add the [resource pool ops file](https://github.com/cloudfoundry/bosh-deployment/blob/master/vsphere/resource-pool.yml) from [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) so that the jumpbox and BOSH director are deployed into the user-provided resource pool. We also add the resource pool to the cloud config so that all BOSH-deployed VMs are deployed into that resource pool.

Do you have a use case where you don't have a resource pool to deploy your VMs into?

**Comment by cdutra** [comment]
@mcnichol You can patch you're create-{jumpbox,director}.sh scripts to remove the `vsphere/resource-pool.yml` ops file. It's a good practice to have resource pool.
Resource Pools on vSphere are virtual resources that don't depend on existing appliance. You can create them at your will.

**Comment by mcnichol** [comment]
Sure. Was aware of that previously. Thinking a better user experience is worth the effort.

Not an issue of ability merely a lack of configuration.

I can close unfortunately

**Comment by cdutra** [comment]
@mcnichol I agree having a flag would be a better user experience. My concern is that pretty much any patch would be a better user experience by adding a flag and with that argument we can have too many flags.

**Comment by hugochinchilla** [comment]
Extracted from [VMware Knowledge Base](https://kb.vmware.com/s/article/1004098)

> Enable VMware DRS on the cluster to enable the Resource Pool option.
> Note: A vSphere Enterprise or Enterprise Plus license is required to enable DRS.

For me this is a huge problem as I need this to work with a VMware essentials license. Is it possible to make the use of resource pools an optional feature?

**Comment by cdutra** [comment]
@hugochinchilla That makes sense. Thanks for the information. Given that situation I agree resource pool should be optional feature in bbl.
