### ISSUE TITLE
Support aws managed nat gateways

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/bosh-bootloader#297]
It would be useful to support [managed nat gateways](https://www.terraform.io/docs/providers/aws/r/nat_gateway.html) on aws. Managed nat gateways support high availability and don't require keeping ami ids [up to date](https://github.com/cloudfoundry/bosh-bootloader/blob/master/terraform/aws/templates/base.tf#L1-L20). Is there any advantage of managing nat gateways with amis and ec2 instances directly over the managed service?

**Comment by aegershman** [comment]
I wonder this as well. We're been using NAT gateways (e.g., the AWS-managed service) in all our AWS PAS foundations. I am not sure why NAT instances (e.g., actual VMs) promoted rather than gateways.

I notice the [`terraforming-aws`](https://github.com/pivotal-cf/terraforming-aws/blob/master/infra/main.tf#L53-L61) project uses them, and the [official "installing PCF on AWS" doc](https://docs.pivotal.io/pivotalcf/2-3/customizing/pcf-aws-manual-config.html#pcfaws-nat) uses NAT instances as well.

Not sure what the rationale is?

**Comment by nmahoney-pivotal** [comment]
Hey @jmcarp. Did anyone ever let you know that we created a [plan patch](https://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/nat-aws/terraform/nat_override.tf) for this? We were hoping you could validate that it is what you are looking for, then we'll make it default bbl behavior.
