### ISSUE TITLE
Should gcp "internal-to-director" fw rule allow 8844 and 8443 by default?

### ISSUE THREAD

**Issue by pvsone** [cloudfoundry/bosh-bootloader#323]
Used bbl 6.7.4 on gcp to bootstrap bosh with credhub and uaa (the default).  Then deployed concourse cluster with credhub integration.  Concourse jobs were not allowed to retrieve parameters from credhub due to timeouts on ports 8844 and 8443 until I added these ports to the "internal-to-director" fw rule.  Should this be the default?

**Comment by cwlbraa** [comment]
Sorry this took so long to get to. This has been discussed before and there are some interesting questions surrounding the suggestion. Some users are doing this via plan patches (@joshzarrabi set it up for pcf releng) but the Infrastructure team generally does not advise using the director credhub as concourse's credhub and we're working on an alternative solution. Here are the problems:

1. director credhub would usually scale linearly with bosh director API, but orthogonally to concourse cluster activity. If concourse uses the director credhub, you end up having to scale director VM memory with the number of running check containers in concourse due to the request load you'll put on the credhub. This is a practical consideration and it can make a (bosh+credhub)+concourse considerably more difficult to operate, especially for the uninitiated. 
2. permissioning scope mismatching: director credhub is single-user, concourse is multi-tenant.
