### ISSUE TITLE
wish I could deploy to a different zone

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-bootloader#324]
No matter which region `west-1` or `central-1` you are going to end up in the first zone of that region for the majority of your deployment which is `a`.

Recently, `west-1a` has seen a lack of capacity and I had no easy way to keep my deployment in west-1 but merely move to either zone `b` or `c`.

I'd love a flag to specify the zone.

**Comment by rowanjacobs** [comment]
Currently, as a workaround while we add this, you can use this `create-director-override.sh` script:
```
#!/bin/sh
bosh create-env \
  ${BBL_STATE_DIR}/bosh-deployment/bosh.yml \
  --state  ${BBL_STATE_DIR}/vars/bosh-state.json \
  --vars-store  ${BBL_STATE_DIR}/vars/director-vars-store.yml \
  --vars-file  ${BBL_STATE_DIR}/vars/director-vars-file.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment/gcp/cpi.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment/jumpbox-user.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment/uaa.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment/credhub.yml \
  -o  ${BBL_STATE_DIR}/bbl-ops-files/gcp/bosh-director-ephemeral-ip-ops.yml \
  --var-file  gcp_credentials_json="${BBL_GCP_SERVICE_ACCOUNT_KEY_PATH}" \
  -v  project_id="${BBL_GCP_PROJECT_ID}" \
  -v  zone="us-west-1b" 
```

**Comment by evanfarrar** [comment]
@zachgersh do you only deploy bosh lites? BBL used to have two features related to zones:

`BBL_GCP_ZONE`: this would determine which API endpoint was used for API calls by terraform. We haven't received out of capacity messages from API endpoints, and you can create a VM in one zone with an API call to a different zone. Since this was sort of confusing and different from our other AWS zone flag and we couldn't demonstrate any reason for choosing a different zone for the API calls we opted to remove this to remove a meaningless decision a user would need to make when BBLing up.

`BBL_AWS_BOSH_AZ`: This would determine which AZ the BOSH director was created in. The BOSH manifest used to use a particular VM type that was not available in a particular zone in AWS. Because the names of AWS *are* randomized by account you have to just avoid this zone based on experience, thus this had to be an option that a human chooses. The BOSH director stopped using that VM type, and that zone became fully functional, so the reasons for this feature were no longer applicable and we removed it.

I could see how a feature like the latter might be somewhat helpful if you BBL up in a pipeline and a new director gets created, that could fail if the first zone is resource constrained, is this what you are experiencing? However, if you do not deploy bosh only lites, then you are hitting capacity problems when you deploy cf-deployment. You could add an operations file to your cloud config to rename the BOSH zone z1 to z3, z3 to z1 etc. Or was there some way you can think of that we can also assist you with that?

**Comment by zachgersh** [comment]
I don't only deploy bosh-lite, these are actually full production like envs.

Yes, the zone (west-1a in particular) is super resource constrained and seems to run out of vms constant. Moving to `central-1a` seems to be fine but bbl appears to just pick `a` all the time and it would have been nice to be able to specify `b` or `c` since I believe this influences the cloud_config among other things.
