### ISSUE TITLE
Advise users to not use version control to manage bbl-state

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/bosh-bootloader#345]
In your readme you advise committing the bbl-state into version control:

https://github.com/cloudfoundry/bosh-bootloader/tree/c12edcf6592f8ebe442a76fae7f551fe42236c80#managing-state

> This should be checked in to version control, so that you have all the information necessary to later destroy or update this environment at a later date.

However, there are secrets in `bbl-state.json`, `.tfstate` and deployment vars files. Version control systems are not designed to be secret stores. You acknowledge this when describing the `vars` dir:

> Consider storing this outside of version control.

If there are secrets in multiple locations, why recommend checking in any of it? I would prefer to guide users into using a secret store like credhub or vault.

**Comment by cwlbraa** [comment]
I believe external credential storage is somewhere on our roadmap, and our most sensitive secrets are in the `vars/` directory. Secret stores definitely deserve a shout out there, but it's really more important that folks store their bbl-state-dirs _somewhere_ rather than nowhere. Our docs should certainly be able to give more balanced advice.

**Comment by joshzarrabi** [comment]
It looks like a lot of the secrets stuff fell off of our roadmap. I agree that we should change the docs to warn people that there is a ton of very sensitive information in the bbl-state and it should be stored in an encrypted blob store.
