### ISSUE TITLE
Network load balancer and websockets not working by default for CF deployment

### ISSUE THREAD

**Issue by diogomatsubara** [cloudfoundry/bosh-bootloader#429]
Now that bbl 7.0.0 deploys a Network Load balancer, when I use it to bring the initial infrastructure to then deploy CF with BOSH (using cf-deployment) connections to the websocket port 4443 end up forwarded to the gorouter on port 4443 but there's nothing listening in that port by default with cf-deployment. Our workaround was to set the listener on 4443 to forward traffic to target group 443 instead of 4443. Not sure if that's the correct fix but in our infrastructure that uses websocket that seems to work fine. Could you advise if this is the correct fix or if we should do something else?

**Comment by notrepo05** [comment]
Hi, thanks for raising this issue! If you are deploying on AWS, then AWS has restrictions on the usage of port 443, so [Loggerator is running on 4443](https://docs.cloudfoundry.org/adminguide/supporting-websockets.html). You can also see in the cf-deployment ops file for aws where we [override the default port to 4443](https://github.com/cloudfoundry/cf-deployment/blob/4eb08d924b77dd0ce492ece5fc18d3afd4dec827/operations/aws.yml#L5). 

What IaaS are you deploying onto?

cc: @Polar-Beard

**Comment by diogomatsubara** [comment]
@notrepo05 I deployed on AWS and the override file I'm using is https://gist.github.com/diogomatsubara/f5de12c4ceb78c2ac1737f0e498b0dc7

I'm not sure I understand your suggestion about Loggregator or if it's relevant for the issue I reported.

We have a service running in one container that needs websocket access. Previously the classic LB deployed by bbl would do the TLS termination and then proxy the request to the router VM and the router VM would route the request to the correct container in the diego-cell. Now with the Network Load Balancer we have requests to port 4443 forwarded directly to the router VMs on port 4443. AFAICT, in the router VM, there's nothing listening to requests on port 4443.

I hope this explanation of our use case makes things a bit clearer. Please, let me know if you need further info and thanks a lot for your reply and help!

**Comment by Polar-Beard** [comment]
Thank you for that explanation @diogomatsubara, that was very helpful. We used to listen on port `4443` when we were using Elastic Load Balancers on AWS, since the ELBs did not support the configuration we needed for websockets (the ELBs reserved port `443` for HTTPS traffic and couldn't be configured to use `TCP`). We needed to use a non-standard port that could use a `TCP` protocol. However, it looks like with Network Load Balancers, we're able to configure port `443` to use `TCP`, so now we're thinking we might be able to remove the `4443` load balancer entirely, since the traffic should be able to flow through the `443` load balancer. 

We understand your problem better now. In your experience, do you see a need to maintain the `4443` load balancer? 

Thanks again!

cc: @notrepo05

**Comment by Polar-Beard** [comment]
We opted to remove the `4443` load balancer: https://github.com/cloudfoundry/bosh-bootloader/commit/ed34ffe2ec1776011f70279d9325df4ee17385ba
