### ISSUE TITLE
Using custom CIDR subnets smaller then /20 fails 'bbl up'

### ISSUE THREAD

**Issue by arthfl** [cloudfoundry/bosh-bootloader#471]
I tried deploying bbl with `vpc_cidr="10.0.0.0/22"` (anonymized IP subnet here) configured in `vars/something.tfvars`.
The `bbl plan` step went through perfectly fine, but then `bbl up` looked like this:
```bash
$ bbl up
step: terraform init
step: terraform apply


Executor apply: Some output has been redacted, use `bbl latest-error` to see it or run again with --debug for additional debug output
```

Checked the errors:
```bash
1$ bbl latest-error

Error: Error running plan: 2 error(s) occurred:

* local.jumpbox_internal_ip: local.jumpbox_internal_ip: cidrhost: prefix of 30 does not accommodate a host numbered 5 in:

${cidrhost(local.internal_cidr, 5)}
* local.director_internal_ip: local.director_internal_ip: cidrhost: prefix of 30 does not accommodate a host numbered 6 in:

${cidrhost(local.internal_cidr, 6)}
```

After a bit of grepping around, i found out this is coming from `terraform/bbl-template.tf`, where following is done:
```bash
$ grep cidrsubnet terraform/bbl-template.tf
  cidr_block = "${cidrsubnet(var.vpc_cidr, 8, 0)}"
  cidr_block        = "${cidrsubnet(var.vpc_cidr, 4, count.index+1)}"
  cidr_block        = "${cidrsubnet(var.vpc_cidr, 8, count.index+2)}"
```
So the first statement adds 8 to the /22, which results in a /30, leaving a subnet with 4 addresses, of which 2 are actually usable.
Not surprising bbl/terraform is not able to add a host #5 into that.

This limitation should at least be documented in docs/advanced-configuration.md. And maybe there is a way to make this more flexible. Some of us might be forced to use "tiny" /22 subnets sometimes :D

**Comment by frank-martens** [comment]
This seems to be a real issue still... so adding comment with details...

`Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # aws_cloudwatch_log_group.bbl will be created
  + resource "aws_cloudwatch_log_group" "bbl" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = (known after apply)
      + name_prefix       = "bbl-env-ur-f3cdb35-log-group"
      + retention_in_days = 0
      + skip_destroy      = false
      + tags              = {
          + "Name" = "bbl-env-urmia-2023-╷
│ Error: Error in function call
│ 
│   on bbl-template.tf line 394, in resource "aws_subnet" "internal_subnets":
│  394:   cidr_block        = "${cidrsubnet(var.vpc_cidr, 4, count.index+1)}"
│     ├────────────────
│     │ while calling cidrsubnet(prefix, newbits, netnum)
│     │ count.index is 18
│     │ var.vpc_cidr is "10.0.0.0/16"
│ 
│ Call to function "cidrsubnet" failed: prefix extension of 4 does not
│ accommodate a subnet numbered 19.
╵
╷
│ Error: Error in function call
│ 
│   on bbl-template.tf line 394, in resource "aws_subnet" "internal_subnets":
│  394:   cidr_block        = "${cidrsubnet(var.vpc_cidr, 4, count.index+1)}"
│     ├────────────────
│     │ while calling cidrsubnet(prefix, newbits, netnum)
│     │ count.index is 16
│     │ var.vpc_cidr is "10.0.0.0/16"
│ 
│ Call to function "cidrsubnet" failed: prefix extension of 4 does not
│ accommodate a subnet numbered 17.
╵
╷
│ Error: Error in function call
│ 
│   on bbl-template.tf line 394, in resource "aws_subnet" "internal_subnets":
│  394:   cidr_block        = "${cidrsubnet(var.vpc_cidr, 4, count.index+1)}"
│     ├────────────────
│     │ while calling cidrsubnet(prefix, newbits, netnum)
│     │ count.index is 17
│     │ var.vpc_cidr is "10.0.0.0/16"
│ 
│ Call to function "cidrsubnet" failed: prefix extension of 4 does not
│ accommodate a subnet numbered 18.`

**Comment by frank-martens** [comment]
Turns out this is probably due to an issue with how many availability zones terraform pulls from aws. For example terraform will add the following to the `../vars/bbl.tfvars` file for aws region _"us-east-1"_:

`availability_zones=["us-east-1-wl1-atl-wlz-1","us-east-1-wl1-bna-wlz-1","us-east-1-wl1-bos-wlz-1","us-east-1-wl1-chi-wlz-1","us-east-1-wl1-clt-wlz-1","us-east-1-wl1-dfw-wlz-1","us-east-1-wl1-dtw-wlz-1","us-east-1-wl1-iah-wlz-1","us-east-1-wl1-mia-wlz-1","us-east-1-wl1-msp-wlz-1","us-east-1-wl1-nyc-wlz-1","us-east-1-wl1-tpa-wlz-1","us-east-1-wl1-was-wlz-1","us-east-1a","us-east-1b","us-east-1c","us-east-1d","us-east-1e","us-east-1f"]`

This appears too many for the "10.0.0.6/16" cidr, so to override this adding less, but more specific, availability zones desired to `../vars/zone.tfvars` does help. 

So for example add the following to `..vars/zone.tfvars` (or whatever is desired for your environment):
`availability_zones=["us-east-1a","us-east-1b","us-east-1c","us-east-1d"]`
