### ISSUE TITLE
manual cloud-config changes destroyed by `bbl unsupported-deploy-bosh-on-aws-for-concourse`

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [cloudfoundry/bosh-bootloader#60]
It would be nice if there were some way make manual updates to cloudconfig persist.

Currently my best bet is to update with bbl, fetch the cloud config, spruce merge in my additions (networks), then `bosh update cloud-config1`

Which isn't so bad; the worst part is that spruce messes up the nicely ordered hashes. It's so much easier to skim when the name keys appear first :)

**Comment by Amit-PivotalLabs** [comment]
Hey folks.

Just an update on this.  We're thinking to perhaps support a mode where bbl just spits out the manifest and cloud config that it would generate, but not actually apply them.  This work would likely be a ways off since we're going to start focusing on GCP support soon.  There might be an intermediate thing we can do which would be to switch from relying on `bosh-init deploy` and instead use `bosh create-env` leveraging the new BOSH CLI.  `bosh create-env` supports overriding the manifest with `-o` flags, and bbl could pass these along to the `create-env` command.  This doesn't help your cloud-config use case, but it's a little easier (if not a bit gross) to deal with the cloud-config like so:

```
bbl up
bosh -t $(bbl director-address) ... cloud-config > /tmp/bbl-cloud-config.yml
./my-custom-cloud-config-modification-script /tmp/bbl-cloud-config.yml > /tmp/cloud-config.yml
bosh -t $(bbl director-address) ... update-cloud-config /tmp/cloud-config.yml
```

**Comment by evanfarrar** [comment]
This mode of operating that Amit described is now in the latest version of bosh-bootloader, 7e29294b470baed77dfde8e1c9ac3efcadb91e76

See https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/advanced.md for a description of how to use this.
