### ISSUE TITLE
Changing the director configuration

### ISSUE THREAD

**Issue by ebabani** [cloudfoundry/bosh-bootloader#64]
Hi,

I asked this question on slack, but putting it here as well for further discussion.

Recently I had a bosh environment set up with bbl, and I wanted to configure the health monitor to enable datadog reporting. Normally I would have updated the bosh manifest and done a bosh-init deploy.

How would I do it if I'm using bbl? I ended up just updating the director manually, but that's not a proper long term solution, since another director deployment would overwrite my configuration.

This morning I tried another method. The state.json that bbl created contains all the info I need to create a bosh.yml, bosh-state.yml and the director private key. 

I created those files, then used bosh-init to update the director, and set the proper health-monitor options.

This worked but was a pain to do. bbl seems to hide the director configuration and makes it impossible to change after setup.

I'm not sure what the roadmap for bbl is. Will bbl manage the director configuration in the future? To me it would make more sense if bbl bootstrapped the environment, then provided me the template and state so I can continue configuring the director as I want with bosh-init.

**Comment by Amit-PivotalLabs** [comment]
Hey @ebabani 

Very sorry for the delayed response, I've been out on vacation.  To answer your question, currently bbl is primarily focused on giving people new to CF and Concourse a very simple BOSH setup, to reduce that barrier to entry.  Many people have asked for things like what you've asked for, so I believe we'll try to support that use case eventually.

Specifically, we're thinking to perhaps support a mode where bbl just spits out the manifest and cloud config that it would generate, but not actually apply them. This work would likely be a ways off since we're going to start focusing on GCP support soon. There might be an intermediate thing we can do which would be to switch from relying on `bosh-init deploy` and instead use `bosh create-env` leveraging the new BOSH CLI. `bosh create-env` supports overriding the manifest with `-o` flags, and bbl could pass these along to the `create-env` command.

**Comment by evanfarrar** [comment]
@ebabani An update: This is now prioritized and partially in flight in our backlog.

**Comment by evanfarrar** [comment]
Hello @ebabani ,

You can now do this in bbl v3, the datadog address / statsd drain can be manipulated by passing an ops file to `up` like `bbl up -o datadog.yml`
