### ISSUE TITLE
Feature request: bbl read-only operations should not require bosh-init

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/bosh-bootloader#69]
I'd like to be able to run `bbl director-address`, `bbl ssh-key` or other read-only operations on my state file without needing `bosh-init` in the path.

Context: we're making a concourse task to run a bosh deploy.  we need some info from the bbl state.  we definitely don't need to `bosh-init` anything.  was surprised to see an error about missing `bosh-init` when running `bbl director-*` commands.

cc: @markstgodard

**Comment by evanfarrar** [comment]
Hey @rosenhouse I know this is ancient now, but given that we are moving to a dependency on bosh v2cli instead of bosh-init do you feel this still affects you? Luan also raised this today, but given the fact that the reason for running director-address was to use it for `bosh target` it can probably be more widely assumed that bosh is installed in most use-cases for bbl.

**Comment by evanfarrar** [comment]
Hello @rosenhouse ,

bbl does not require read bosh-init at all. There may still be some commands which erroneously require BOSH clie, but it seemed OK because most of the usage of the read-only commands is to feed the result to the bosh cli.

In addition, rather than running the `bbl director-*` commands there is now a convenient one liner that runs them all and sets them to BOSH environment variables:
```
$# eval "$(bosh print-env)"
```

**Comment by rosenhouse** [comment]
Sweet, thanks.  I'm looking forwarding to upgrading to bbl3!
